### ISSUE TITLE
Links missing from doc page

### ISSUE THREAD

**Issue by systemnotes** [dappnode/DAppNodeDocs#57] opened 2021-07-01 21:22 UTC
**Describe the bug**
Missing links.
https://docs.dappnode.io/get-started/user-guide/ui/access/local-proxy
https://docs.dappnode.io/get-started/user-guide/ui/access/vpn#wireguard
https://docs.dappnode.io/get-started/user-guide/ui/access/vpn#openvpn
https://docs.dappnode.io/get-started/user-guide/ui/access/local-proxy

From this page
https://docs.dappnode.io/get-started/installation/custom-hardware/installation/script/

These links are broken.
    Local Proxy
    Wifi
    Wireguard
    OpenVPN

**To Reproduce**

**Expected behavior**

Doc page should load.

**Screenshots**

**DAppNode version:**

- Package version: 
- OS: 
- Browser 

**Additional context**

**Comment by tropicar** [comment] 2021-07-14 13:05
It's strange, because if you navigate to https://docs.dappnode.io/get-started/installation/custom-hardware/installation/script manually the URL is that and works, but you are in the page with the URL https://docs.dappnode.io/get-started/installation/custom-hardware/installation/script/ that finishes in '/', i have to research if you get that link in some place from external or in the own documentattion

**Comment by tropicar** [comment] 2022-03-08 16:28
The problem is fixed nowdays,, thank you for the feedback

**Closed by tropicar** 2022-03-08 16:28 UTC
